### ISSUE TITLE
store_attr() doesn't seem to work with ABC in python >=3.7

### ISSUE THREAD

**Issue by GilesStrong** [fastai/fastcore#295]
Hi, I recently encountered a problem with using the `store_attr`  method in classes which inherit from `abc.ABC`, however this problem only seems to occur in python v3.7 onwards.

As a test:
```
from abc import ABC
from fastcore.all import store_attr

class T0(ABC):
    def __init__(self,a,b,c):
        store_attr()
        print(self.a)
        print(self.__stored_args__)

T0(1,1,1)
```
will print:
```
1
{'a': 1, 'b': 1, 'c': 1}
```
in python 3.6.13. But in python 3.7.10 results in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in __init__
AttributeError: 'T0' object has no attribute 'a'
```

Python 3.7's [what's new](https://docs.python.org/3/whatsnew/3.7.html) states that "Most functions and methods in abc have been rewritten in C. This makes creation of abstract base classes, and calling isinstance() and issubclass() on them 1.5x faster."
As part of this rewrite, `ABC` seems to have been given the `__slots__` attribute, meaning that when `store_args` is `None`, the `__stored_args__` dict is not created (https://github.com/fastai/fastcore/blob/master/fastcore/basics.py#L296)

To ensure compatibility, one has to explicitly state the attribute names and set `store_args` to True:
```
>>> class T1(ABC):
    def __init__(self,a,b,c):
        store_attr('a,b,c', store_args=True)
        print(self.a)
        print(self.__stored_args__)
... 
>>> T1(1,1,1)
1
{'a': 1, 'b': 1, 'c': 1}
<__main__.T1 object at 0x7f2c2b7a8d10>
```
Personally, I think this erodes the simplicity of just calling `store_attr()`, however I can't comment more without knowing why it checks for `__slots__`.

**Comment by GilesStrong** [comment]
Hi, I understand that everyone's super busy these days, but I'm just wondering if one of the devs could take a moment to let me know if this is expected behaviour I should work around, or an unforeseen effect I should submit a fix for? Thanks.

**Comment by jph00** [comment]
Hi @GilesStrong , sorry for the delayed response. FYI feel free to at-mention me to ensure I don't miss messages. Making this compatible with slots is probably a level of complexity that I'd rather avoid, so I'd suggest working around the issue.
